# config.yaml
dataset: "zind_data_set_80_fov"
dataset_path: "/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_Plan_Localization/data/zind"
ckpt_path: "./logs/zind/fov_80_correct_scale_final/"
epochs: 100
batch_size: 8
lr: 0.001
shape_loss_weight: 20
model_type: "depth"

# Depth net parameters
depth_net:
  L: 0
  D: 128
  d_min: 0.1
  d_max: 15.0
  d_hyp: -0.2
  F_W: 3 / 5

# Augmentation settings
augmentation:
  add_rp: True
  roll: 0
  pitch: 0
