# config_evaluate_top_k.yaml

dataset: "structured3d_perspective_full"
dataset_path: "/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full"
top_k_results_dir: "/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/top_k/results_dist_0.2_top_20_with_augmentations"
split_file: "/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/data/test_data_set_full/structured3d_perspective_full/split.yaml"
checkpoint: "/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/top_k/logs/best_k_net_bs-16_ep-100_fp-True_time-20250123-1222-train_100_epochs/final_best_k_net_checkpoint.ckpt"  
ckpt_path: "/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/top_k/evaluate_results"  
use_fp: True
poses_filename: "poses.txt"
epochs: 100  # You can keep this as is or adjust if needed
batch_size: 16
lr: 0.001
num_workers: 8
num_candidates: 20



# Depth network parameters
D: 128
d_min: 0.1
d_max: 15.0
d_hyp: -0.2
# Semantic network parameters
num_classes: 4

log_dir_depth: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/Final_wights/depth/final_depth_model_checkpoint.ckpt'
log_dir_semantic: '/datadrive2/CRM.AI.Research/TeamFolders/Email/repo_yuval/FloorPlan/Semantic_Floor_plan_localization/modules/Final_wights/semantic/final_semantic_model_checkpoint.ckpt'